version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: task_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - task_net

  server:
    build: ./server
    container_name: task_server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskmanagement
      - JWT_SECRET=your_docker_jwt_secret_change_this_in_production
    depends_on:
      - mongo
    networks:
      - task_net

  client:
    build: ./client
    container_name: task_client
    ports:
      - "8081:80"
    depends_on:
      - server
    networks:
      - task_net

volumes:
  mongo_data:


networks:
  task_net:
    driver: bridge
